version: '3.1'

services:
  api:
    image: voting-api:debug
    build:
      context: ./src/Voting.Api/bin/PublishOutput/
      dockerfile: Dockerfile.debug
    ports: 
      - "81:80"
    environment:
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113 
      - ASPNETCORE_ENVIRONMENT=Development
    volumes: 
      - ./src/Voting.Api/bin/PublishOutput/:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
  
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"